### ISSUE TITLE
Make country categories offline

### ISSUE THREAD

**Issue by joaomanaia** [joaomanaia/newquiz#65]
Currently all country categories from multi choice quiz and comparison quiz require internet connection, to the end user it is better to have more categories not depending on the internet connection.

### Tasks done:

- [x] Update the local countries json file with the remaining data
- [x] Save all the countries flags locally
- [x] Make an option in the remove config to change from local flags to the remote flags. (local default)

Comparison quiz

- [ ] Create a new repository to load the country questions from the local device and not from the NewQuiz api
